#!/bin/bash

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

PORT=9000
if [ ! -z "$1" ]; then
  PORT=$1
fi

docker run --rm -it -v $(pwd):/site rancherlabs/website:dev minify-images
