#!/bin/bash

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

echo "Pulling Theme..." && \
docker pull rancherlabs/website-theme:latest && \
echo "Building Image..." && \
docker build -t rancher/docs:latest . && \
echo "Pushing Image..." && \
docker push rancher/docs:latest && \
echo "OK"
